<a href="https://colab.research.google.com/github/Rosari03/Metodos-Numericos/blob/main/interpolacion_Nevill.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Interpolacion iterada de Neville

Este metodo es una lgortimno numerico para calcular el valor de un polinomio interpolante en un punto dado nosotros lo llamaremos *Z* sin necesidad de recontruir todo el polinomio symbolicamente



# El metodo para encontrar este polinomio
Basicamente tenemos que seguir la siguiente formula

$Q_{I,J}= \frac{(x-x_{i,j})Q_{i,j-1}-(x-x_i)Q_{i-1,j-1}}{(x_i-x_{i-j})}$

donde nos dara como resultado un valor interpolado aproximado

In [ ]:
import sympy as sp
from sympy import sympify, lambdify
import numpy as np
import matplotlib.pyplot as plt
import math


In [ ]:

def nevill(X: list[float] | np.ndarray, y: list[float] | np.ndarray, x:float):
    n = len(X)
    nev = np.zeros((n, n), dtype=object)

    # Primera columna: los valores de y
    for i in range(n):
        nev[i, 0] = y[i]

    # Rellenar la tabla de Neville
    for j in range(1, n):
        for i in range(j, n):
            numer = (x - X[i - j]) * nev[i, j - 1] - (x - X[i]) * nev[i - 1, j - 1]
            denom = X[i] - X[i - j]
            nev[i, j] = numer / denom
    return nev

In [ ]:
X=[1,1.3,1.6,1.9,2.2]
Y=[.7651977,0.6200860,.4554022,.2818186,0.1103623]
z=1.5
#Z es el valor al que queremos aproximar
nev=nevill(X,Y,z)
print(nev)


[[0.7651977 0 0 0 0]
 [0.620086 0.5233448666666667 0 0 0]
 [0.4554022 0.5102968 0.5124714777777778 0 0]
 [0.2818186 0.5132634 0.5112856666666666 0.5118126938271604 0]
 [0.1103623 0.5104269999999997 0.5137361333333335 0.5118302148148148
  0.5118199942386831]]
